In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error,root_mean_squared_error,r2_score,accuracy_score
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder

In [19]:
df=pd.read_csv("C:\\Users\\rajh9\\Downloads\\placementdata.csv")
df=df.drop('StudentID',axis=1)
df.head()


CGPA  Internships  Projects  Workshops/Certifications  AptitudeTestScore  \
0   7.5            1         1                         1                 65   
1   8.9            0         3                         2                 90   
2   7.3            1         2                         2                 82   
3   7.5            1         1                         2                 85   
4   8.3            1         2                         2                 86   

   SoftSkillsRating ExtracurricularActivities PlacementTraining  SSC_Marks  \
0               4.4                        No                No         61   
1               4.0                       Yes               Yes         78   
2               4.8                       Yes                No         79   
3               4.4                       Yes               Yes         81   
4               4.5                       Yes               Yes         74   

   HSC_Marks PlacementStatus  
0         79       NotPlaced  
1         82          Placed  
2         80       NotPlaced  
3         80          Placed  
4         88          Placed

In [4]:
df.isnull().sum()

CGPA                         0
Internships                  0
Projects                     0
Workshops/Certifications     0
AptitudeTestScore            0
SoftSkillsRating             0
ExtracurricularActivities    0
PlacementTraining            0
SSC_Marks                    0
HSC_Marks                    0
PlacementStatus              0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   CGPA                       10000 non-null  float64
 1   Internships                10000 non-null  int64  
 2   Projects                   10000 non-null  int64  
 3   Workshops/Certifications   10000 non-null  int64  
 4   AptitudeTestScore          10000 non-null  int64  
 5   SoftSkillsRating           10000 non-null  float64
 6   ExtracurricularActivities  10000 non-null  object 
 7   PlacementTraining          10000 non-null  object 
 8   SSC_Marks                  10000 non-null  int64  
 9   HSC_Marks                  10000 non-null  int64  
 10  PlacementStatus            10000 non-null  object 
dtypes: float64(2), int64(6), object(3)
memory usage: 859.5+ KB


In [6]:
df.describe()

CGPA   Internships      Projects  Workshops/Certifications  \
count  10000.000000  10000.000000  10000.000000              10000.000000   
mean       7.698010      1.049200      2.026600                  1.013200   
std        0.640131      0.665901      0.867968                  0.904272   
min        6.500000      0.000000      0.000000                  0.000000   
25%        7.400000      1.000000      1.000000                  0.000000   
50%        7.700000      1.000000      2.000000                  1.000000   
75%        8.200000      1.000000      3.000000                  2.000000   
max        9.100000      2.000000      3.000000                  3.000000   

       AptitudeTestScore  SoftSkillsRating     SSC_Marks     HSC_Marks  
count       10000.000000      10000.000000  10000.000000  10000.000000  
mean           79.449900          4.323960     69.159400     74.501500  
std             8.159997          0.411622     10.430459      8.919527  
min            60.000000          3.000000     55.000000     57.000000  
25%            73.000000          4.000000     59.000000     67.000000  
50%            80.000000          4.400000     70.000000     73.000000  
75%            87.000000          4.700000     78.000000     83.000000  
max            90.000000          4.800000     90.000000     88.000000

In [7]:
numeric_df = df.select_dtypes(include=['int64', 'float64'])
numeric_df.corr()


CGPA  Internships  Projects  \
CGPA                      1.000000     0.280601  0.435928   
Internships               0.280601     1.000000  0.309196   
Projects                  0.435928     0.309196  1.000000   
Workshops/Certifications  0.349686     0.279110  0.377865   
AptitudeTestScore         0.461250     0.320725  0.540339   
SoftSkillsRating          0.383547     0.273691  0.450294   
SSC_Marks                 0.404971     0.279837  0.499421   
HSC_Marks                 0.462313     0.317149  0.535708   

                          Workshops/Certifications  AptitudeTestScore  \
CGPA                                      0.349686           0.461250   
Internships                               0.279110           0.320725   
Projects                                  0.377865           0.540339   
Workshops/Certifications                  1.000000           0.388061   
AptitudeTestScore                         0.388061           1.000000   
SoftSkillsRating                          0.342397           0.515400   
SSC_Marks                                 0.373045           0.513044   
HSC_Marks                                 0.418442           0.565105   

                          SoftSkillsRating  SSC_Marks  HSC_Marks  
CGPA                              0.383547   0.404971   0.462313  
Internships                       0.273691   0.279837   0.317149  
Projects                          0.450294   0.499421   0.535708  
Workshops/Certifications          0.342397   0.373045   0.418442  
AptitudeTestScore                 0.515400   0.513044   0.565105  
SoftSkillsRating                  1.000000   0.430734   0.466912  
SSC_Marks                         0.430734   1.000000   0.524916  
HSC_Marks                         0.466912   0.524916   1.000000

In [8]:
le=LabelEncoder()
y=le.fit_transform(df['PlacementStatus'])
y.reshape(1,-1)

array([[0, 1, 0, ..., 1, 1, 0]], shape=(1, 10000))

In [9]:
ct=ColumnTransformer(transformers=[('col1',OneHotEncoder(sparse_output=False,drop='first'),['ExtracurricularActivities','PlacementTraining'])],remainder='passthrough')

In [10]:
dF=ct.fit_transform(df)
new_columns = ct.get_feature_names_out()
new_df=pd.DataFrame(dF,columns=new_columns)
new_df

col1__ExtracurricularActivities_Yes col1__PlacementTraining_Yes  \
0                                    0.0                         0.0   
1                                    1.0                         1.0   
2                                    1.0                         0.0   
3                                    1.0                         1.0   
4                                    1.0                         1.0   
...                                  ...                         ...   
9995                                 1.0                         0.0   
9996                                 0.0                         0.0   
9997                                 1.0                         1.0   
9998                                 1.0                         1.0   
9999                                 0.0                         0.0   

     remainder__CGPA remainder__Internships remainder__Projects  \
0                7.5                      1                   1   
1                8.9                      0                   3   
2                7.3                      1                   2   
3                7.5                      1                   1   
4                8.3                      1                   2   
...              ...                    ...                 ...   
9995             7.5                      1                   1   
9996             7.4                      0                   1   
9997             8.4                      1                   3   
9998             8.9                      0                   3   
9999             8.4                      0                   1   

     remainder__Workshops/Certifications remainder__AptitudeTestScore  \
0                                      1                           65   
1                                      2                           90   
2                                      2                           82   
3                                      2                           85   
4                                      2                           86   
...                                  ...                          ...   
9995                                   2                           72   
9996                                   0                           90   
9997                                   0                           70   
9998                                   2                           87   
9999                                   1                           66   

     remainder__SoftSkillsRating remainder__SSC_Marks remainder__HSC_Marks  \
0                            4.4                   61                   79   
1                            4.0                   78                   82   
2                            4.8                   79                   80   
3                            4.4                   81                   80   
4                            4.5                   74                   88   
...                          ...                  ...                  ...   
9995                         3.9                   85                   66   
9996                         4.8                   84                   67   
9997                         4.8                   79                   81   
9998                         4.8                   71                   85   
9999                         3.8                   62                   66   

     remainder__PlacementStatus  
0                     NotPlaced  
1                        Placed  
2                     NotPlaced  
3                        Placed  
4                        Placed  
...                         ...  
9995                  NotPlaced  
9996                     Placed  
9997                     Placed  
9998                     Placed  
9999                  NotPlaced  

[10000 rows x 11 columns]

In [11]:
cols=['col1__ExtracurricularActivities_Yes','col1__PlacementTraining_Yes']
new_df[cols]=new_df[cols].astype(int)
new_df

col1__ExtracurricularActivities_Yes  col1__PlacementTraining_Yes  \
0                                       0                            0   
1                                       1                            1   
2                                       1                            0   
3                                       1                            1   
4                                       1                            1   
...                                   ...                          ...   
9995                                    1                            0   
9996                                    0                            0   
9997                                    1                            1   
9998                                    1                            1   
9999                                    0                            0   

     remainder__CGPA remainder__Internships remainder__Projects  \
0                7.5                      1                   1   
1                8.9                      0                   3   
2                7.3                      1                   2   
3                7.5                      1                   1   
4                8.3                      1                   2   
...              ...                    ...                 ...   
9995             7.5                      1                   1   
9996             7.4                      0                   1   
9997             8.4                      1                   3   
9998             8.9                      0                   3   
9999             8.4                      0                   1   

     remainder__Workshops/Certifications remainder__AptitudeTestScore  \
0                                      1                           65   
1                                      2                           90   
2                                      2                           82   
3                                      2                           85   
4                                      2                           86   
...                                  ...                          ...   
9995                                   2                           72   
9996                                   0                           90   
9997                                   0                           70   
9998                                   2                           87   
9999                                   1                           66   

     remainder__SoftSkillsRating remainder__SSC_Marks remainder__HSC_Marks  \
0                            4.4                   61                   79   
1                            4.0                   78                   82   
2                            4.8                   79                   80   
3                            4.4                   81                   80   
4                            4.5                   74                   88   
...                          ...                  ...                  ...   
9995                         3.9                   85                   66   
9996                         4.8                   84                   67   
9997                         4.8                   79                   81   
9998                         4.8                   71                   85   
9999                         3.8                   62                   66   

     remainder__PlacementStatus  
0                     NotPlaced  
1                        Placed  
2                     NotPlaced  
3                        Placed  
4                        Placed  
...                         ...  
9995                  NotPlaced  
9996                     Placed  
9997                     Placed  
9998                     Placed  
9999                  NotPlaced  

[10000 rows x 11 columns]

In [12]:
x=new_df.iloc[:,:-1].values
x

array([[0, 0, 7.5, ..., 4.4, 61, 79],
       [1, 1, 8.9, ..., 4.0, 78, 82],
       [1, 0, 7.3, ..., 4.8, 79, 80],
       ...,
       [1, 1, 8.4, ..., 4.8, 79, 81],
       [1, 1, 8.9, ..., 4.8, 71, 85],
       [0, 0, 8.4, ..., 3.8, 62, 66]], shape=(10000, 10), dtype=object)

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

array([[1, 0, 8.2, ..., 4.8, 61, 75],
       [1, 1, 8.4, ..., 4.5, 81, 83],
       [1, 1, 8.1, ..., 4.6, 73, 87],
       ...,
       [1, 1, 8.1, ..., 4.8, 78, 84],
       [1, 1, 8.0, ..., 4.8, 81, 88],
       [1, 1, 7.4, ..., 4.3, 67, 73]], shape=(8000, 10), dtype=object)

In [14]:
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)


LogisticRegression(max_iter=1000)

In [18]:
y_predict=model.predict(x_test)
y_predict

array([1, 1, 0, ..., 1, 1, 1], shape=(2000,))

In [36]:
y_test

array([0, 0, 0, ..., 1, 1, 1], shape=(2000,))

In [37]:
acc=accuracy_score(y_test,y_predict)
acc

0.8005

In [38]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train1=sc.fit_transform(x_train)
x_test2=sc.transform(x_test)
x_test2

array([[ 0.83944418,  0.60835649,  0.00358533, ..., -0.80216324,
         1.98206921,  1.06084759],
       [ 0.83944418,  0.60835649,  1.25065497, ...,  0.90729492,
        -0.40392495,  1.17289022],
       [-1.19126444, -1.64377304, -1.55525173, ..., -0.80216324,
        -1.35832261, -0.84387705],
       ...,
       [ 0.83944418,  0.60835649,  0.78300385, ...,  0.90729492,
         1.31399084,  0.94880497],
       [ 0.83944418,  0.60835649,  1.09477127, ...,  0.90729492,
         1.40943061,  0.94880497],
       [ 0.83944418,  0.60835649,  0.93888756, ...,  1.15150323,
         1.12311131,  0.61267709]], shape=(2000, 10))

In [39]:
model=LogisticRegression(max_iter=1000)
model.fit(x_train1,y_train)

LogisticRegression(max_iter=1000)

In [42]:
y_predict=model.predict([])
y_predict

array([1, 1, 0, ..., 1, 1, 1], shape=(2000,))

In [43]:
acc=accuracy_score(y_test,y_predict)
acc

0.8005

from sklearn.neighbors import kNeighborsClassif

In [47]:
from sklearn.neighbors import KNeighborsClassifier


In [54]:
model=KNeighborsClassifier(n_neighbors=114)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([1, 0, 0, ..., 1, 1, 1], shape=(2000,))

In [55]:
y_test

array([0, 0, 0, ..., 1, 1, 1], shape=(2000,))

In [56]:
acc=accuracy_score(y_test,y_pred)

In [57]:
acc

0.79

In [62]:
model=KNeighborsClassifier(n_neighbors=1)
model.fit(x_train1,y_train)
y_pred=model.predict(x_test2)
y_pred

array([1, 0, 0, ..., 1, 1, 1], shape=(2000,))

In [65]:
acc=accuracy_score(y_pred,y_test)

In [66]:
acc

0.719